### ISSUE TITLE
haproxy 未转发真实IP

### ISSUE THREAD

**Issue by jimorsm** [tcp-nanqinlang/general#10]
lkl 实现bbr中，haproxy并未转发真实ip，nginx获取的remote_addr 为局域网ip10.0.0.2

**Comment by nanqinlang** [comment]
没明白你说的 `remote_addr` 是指什么  
lkl 的 `haproxy` 并不是直接转发本地的 127.0.0.1，它是在本地开一个 `10.0.0.1` 的 tap，然后把这个 tap 转发到 `10.0.0.2`

**Comment by jimorsm** [comment]
80和443端口启用bbr，网页环境：php+nginx，获取到的访问用户ip是10.0.0.1，不是真实IP
http://www.cnblogs.com/shiyiwen/p/5032449.html
http://blog.51cto.com/shanks/1307607
http://blog.csdn.net/chaimyu/article/details/49000151
http://www.it610.com/article/3369300.htm

2017-12-20 23:46 GMT+08:00 南琴浪 <notifications@github.com>:

**Comment by nanqinlang** [comment]
我觉得你是不是想太多了，只要你安装 lkl 时指定的端口包括了 `80 443`，就已经成功 lkl 了。根本就不用纠结什么真实 IP。  
关于你说的 真实IP 是 `10.0.0.2`，你是不是看的 `accesslog`？那是理所应当的，你自己在本地 forward 了一遍，这时候 remoteaddr 已经改变了。至于怎么保持 remoteaddr 为客户实际IP，你自己研究吧。
