### ISSUE TITLE
centos 7 ovz开机不会自启动啊

### ISSUE THREAD

**Issue by wsj195328** [tcp-nanqinlang/general#11]
lkl-centos-1.1.0.sh

**Comment by wsj195328** [comment]
找到方案了，在centos7中,/etc/rc.d/rc.local文件的权限被降低了,开机的时候执行在自己的脚本是不能起动一些服务的,执行下面的命令可以文件标记为可执行的文件

chmod +x /etc/rc.d/rc.local

**Comment by nanqinlang** [comment]
原来如此，感谢反馈，我会写到脚本里。
