### ISSUE TITLE
魔改 BBR for Ubuntu-kernel-daily-20180105

### ISSUE THREAD

**Issue by nanqinlang** [tcp-nanqinlang/general#13]
## why daily
![default](https://user-images.githubusercontent.com/26526543/34601584-93967070-f237-11e7-98a4-6814496492dc.png)
http://kernel.ubuntu.com/~kernel-ppa/mainline/daily/current/CHANGES

that's why i choose a daily kernel to use.

## enable tcp_nanqinlang
to enable tcp_nanqinlang for that kernel, you should run the following directive:
```bash
wget http://kernel.ubuntu.com/~kernel-ppa/mainline/daily/2018-01-05/linux-image-4.15.0-999-lowlatency_4.15.0-999.201801050201_amd64.deb
wget http://kernel.ubuntu.com/~kernel-ppa/mainline/daily/2018-01-05/linux-headers-4.15.0-999_4.15.0-999.201801050201_all.deb
wget http://kernel.ubuntu.com/~kernel-ppa/mainline/daily/2018-01-05/linux-headers-4.15.0-999-lowlatency_4.15.0-999.201801050201_amd64.deb

dpkg -i linux-image-4.15.0-999-lowlatency_4.15.0-999.201801050201_amd64.deb
dpkg -i linux-headers-4.15.0-999_4.15.0-999.201801050201_all.deb
apt-get install -y libelf1
dpkg -i linux-headers-4.15.0-999-lowlatency_4.15.0-999.201801050201_amd64.deb
update-grub
```
then, `reboot` your device, then run these:
```bash
wget https://github.com/nanqinlang-tcp/tcp_nanqinlang/releases/download/daily-20180105/tcp_nanqinlang.c

# debian7/8
wget -O Makefile https://raw.githubusercontent.com/nanqinlang-tcp/tcp_nanqinlang/master/Makefile/Makefile-Debian7or8
# debian9
wget -O Makefile https://raw.githubusercontent.com/nanqinlang-tcp/tcp_nanqinlang/master/Makefile/Makefile-Debian9

make && make install

echo -e "\nnet.core.default_qdisc=fq" >> /etc/sysctl.conf
echo -e "net.ipv4.tcp_congestion_control=nanqinlang\c" >> /etc/sysctl.conf
sysctl -p
```

**Comment by nanqinlang** [comment]
to use this script, you just need to run this:
```bash
wget https://github.com/nanqinlang-tcp/tcp_nanqinlang/releases/download/20180105-aptupgrade/20180105-aptupgrade-to-fixmeltdown.sh
bash 20180105-aptupgrade-to-fixmeltdown.sh
```

the following is the source of this script
```bash
apt-source-get(){
	cd /etc/apt
	mv sources.list  sources.list.bak
	wget -O sources.list https://raw.githubusercontent.com/nanqinlang/sources.list/master/us.sources_stretch.list
}

upgrade(){
	apt-get update
	apt-get dist-upgrade -y
}

apt-source-restore(){
	mv -f /etc/apt/sources.list.bak  /etc/apt/sources.list
}

restart(){
	echo -e "\nplease ensure the above progress has not mistake, then reboot your device ."
	echo -e "\nso are you sure you want a reboot ?"
	echo "1.yes\n2.no"
	read -p "(please choose):" sure
	[[ "${sure}" = "1" ]] && reboot
}



echo -e "now will start Debian Meltdown fixing process via apt-upgrade :\n"
apt-source-get
upgrade
apt-source-restore
restart
```

**Comment by love4taylor** [comment]
CentOS 7
kernel-ml-4.14.12-1
可正常通过编译 使用暂时正常

_Sent from my Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nanqinlang** [comment]
@Love4Taylor  
`CentOS` 那边的 PTI 是哪个版本内核更新的, 我还没去看呢

**Comment by nanqinlang** [comment]
there is a script:
```bash
wget https://github.com/nanqinlang-tcp/tcp_nanqinlang/releases/download/daily-20180105/tcp_nanqinlang-daily20180105.sh
bash tcp_nanqinlang-daily20180105.sh
```
requirement, only: `Debian7+  64bit  KVM`

usage:
1. run first choice
2. reboot
3. run second choice

**Comment by teochen** [comment]
I don't know what's going wrong when I run second choice


make: *** [install] Error 1
net.ipv4.ip_forward = 1
fs.file-max = 51200
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.core.netdev_max_backlog = 250000
net.core.somaxconn = 4096
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
sysctl: cannot stat /proc/sys/net/ipv4/tcp_tw_recycle: No such file or directory
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_keepalive_time = 1200
net.ipv4.ip_local_port_range = 10000 65000
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_mem = 25600 51200 102400
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.tcp_mtu_probing = 1
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = nanqinlang
[Error] tcp_nanqinlang not installed !

**Comment by nanqinlang** [comment]
@teochen  
`make: *** [install] Error 1` 这行附近上下的信息呢

**Comment by teochen** [comment]
tcp_nanqinlang.c                 100%[===========================================================>]  34.45K  --.-KB/s   in 0.1s   

2018-01-07 09:07:12 (273 KB/s) - ‘tcp_nanqinlang.c’ saved [35274/35274]

--2018-01-07 09:07:12--  https://raw.githubusercontent.com/nanqinlang-tcp/tcp_nanqinlang/master/Makefile/Makefile-Debian7or8
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 412 [text/plain]
Saving to: ‘Makefile’

Makefile                         100%[===========================================================>]     412  --.-KB/s   in 0s     

2018-01-07 09:07:12 (1.82 MB/s) - ‘Makefile’ saved [412/412]

make -C /lib/modules/`uname -r`/build M=`pwd` modules CC=/usr/bin/gcc-4.9
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-999-lowlatency'
  CC [M]  /home/tcp_nanqinlang/tcp_nanqinlang.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/tcp_nanqinlang/tcp_nanqinlang.mod.o
  LD [M]  /home/tcp_nanqinlang/tcp_nanqinlang.ko
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-999-lowlatency'
install tcp_nanqinlang.ko /lib/modules/`uname -r`/kernel/net/ipv4
insmod /lib/modules/`uname -r`/kernel/net/ipv4/tcp_nanqinlang.ko
insmod: ERROR: could not insert module /lib/modules/4.15.0-999-lowlatency/kernel/net/ipv4/tcp_nanqinlang.ko: File exists
Makefile:10: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by nanqinlang** [comment]
@teochen  
运行 `lsmod` 看看

**Comment by Gordon-shin** [comment]
make -C /lib/modules/`uname -r`/build M=`pwd` modules CC=/usr/bin/gcc-4.9
make[1]: Entering directory `/usr/src/linux-headers-4.15.0-999-lowlatency'
  Building modules, stage 2.
  MODPOST 0 modules
make[1]: Leaving directory `/usr/src/linux-headers-4.15.0-999-lowlatency'
install tcp_nanqinlang.ko /lib/modules/`uname -r`/kernel/net/ipv4
install: cannot stat ‘tcp_nanqinlang.ko’: No such file or directory
make: *** [install] Error 1
fs.file-max = 51200
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.core.netdev_max_backlog = 250000
net.core.somaxconn = 4096
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
sysctl: cannot stat /proc/sys/net/ipv4/tcp_tw_recycle: No such file or directory
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_keepalive_time = 1200
net.ipv4.ip_local_port_range = 10000 65000
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_mem = 25600 51200 102400
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.tcp_mtu_probing = 1
net.core.default_qdisc = fq
sysctl: setting key "net.ipv4.tcp_congestion_control": No such file or directory
net.ipv4.tcp_congestion_control = nanqinlang
