### ISSUE TITLE
安装LKL后frp无法正常运行

### ISSUE THREAD

**Issue by engineerlzk** [tcp-nanqinlang/general#16]
如题，我是在OVZ主机CentOS7（64位）系统中安装LKL的，在安装过程中提示：epel/x86_64/primary_db         FAILED，但随后的提示中却又提示该文件6.2MB似乎成功下载。按提示安装完成，并且查看状态显示运行成功，但发现它会自行消亡处于非运行状态。
关键的一点，迅影LKL后，frp服务端无法正常运行，连dashboard都无法访问（我的提速端口设置为80-65000），关闭BBR后成功访问

**Comment by nanqinlang** [comment]
可能是 iptables 的规则和 frp 冲突了吧。解决方案目前我也不清楚。

**Comment by engineerlzk** [comment]
好的，我再折腾哈

**Comment by nanqinlang** [comment]
关于 `epel/x86_64/primary_db FAILED` 能否提供更多信息呢。

不过这个 issue 过了这么久了，还能不能复现（

**Comment by nanqinlang** [comment]
no reply for a long time
