### ISSUE TITLE
配置超过了40个端口就会报错

### ISSUE THREAD

**Issue by FsHtroy** [tcp-nanqinlang/general#18]
[    0.117726] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    0.118478] Warning: unable to open an initial console.
[    0.118514] This architecture does not have kernel memory protection.
[    3.214198] random: fast init done
Segmentation fault

Rinetd版本

**Comment by nanqinlang** [comment]
感谢反馈。

不过填了 40 个端口也是。。。

我之后看怎么写端口段吧。

然后，Nico 满分。

**Comment by nanqinlang** [comment]
看了下你贴的这段，这些输出信息都是正常的

所以如果可以的话，能提供完整的（或者更多的）输出信息就更好了，输出地址在 `/home/tcp_nanqinlang/nohup.out`
