### ISSUE TITLE
使用Clang5.0在4.13和4.14kernel上会无法加载

### ISSUE THREAD

**Issue by ghost** [tcp-nanqinlang/general#2]
可以编译通过但是执行insmod会一直卡住，但是用gcc编译后可以正确加载。

**Comment by ghost** [comment]
使用clang4.0以后错误如下：
[  229.283237] tcp_nanqinlang: loading out-of-tree module taints kernel.                                                      [  229.283310] tcp_nanqinlang: module verification failed: signature and/or required key missing - tainting kernel            [  229.283385] tcp_nanqinlang: Unknown symbol mcount (err 0)

**Comment by nanqinlang** [comment]
是滴，这个东东就是要 `gcc` 做编译器，至于 `clang` 为么不行我也不清楚。

**Comment by ghost** [comment]
@nanqinlang好吧,谢谢了
