### ISSUE TITLE
好像有个BUG ，前几天安装的好好的现在删掉重装 不行啊

### ISSUE THREAD

**Issue by abclai** [tcp-nanqinlang/general#23]
--2018-03-10 19:30:31--  https://github.com/nanqinlang-tcp/tcp_nanqinlang/releases/download/rinetd/rinetd_bbr.module
正在解析主机 github.com (github.com)... 192.30.253.113, 192.30.253.112
正在连接 github.com (github.com)|192.30.253.113|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 404 Not Found
2018-03-10 19:30:32 错误 404：Not Found。

chmod: 无法访问"rinetd_bbr.module": 没有那个文件或目录
[Info] 输入你想加速的端口
(多个端口号用空格隔开。暂不支持端口段。默认使用 443):1000 2000
nohup: 把输出追加到"nohup.out"
nohup: 无法运行命令"./rinetd_bbr.module": 没有那个文件或目录
nohup: 把输出追加到"nohup.out"
nohup: 无法运行命令"./rinetd_bbr.module": 没有那个文件或目录
nohup: 把输出追加到"nohup.out"
nohup: 无法运行命令"./rinetd_bbr.module": 没有那个文件或目录
[Error] tcp_nanqinlang not running, please check !

**Comment by nanqinlang** [comment]
emmmmmm... 脚本已经更新啦，新脚本下载地址在文章有
