### ISSUE TITLE
get_url()  中 bit=`uname -m` 条件判断不全面

### ISSUE THREAD

**Issue by q158073378252010** [tcp-nanqinlang/general#29]
在 bwg 主机商 kvm debian_9（32bit） get_url() 中 bit=`uname -m` 取出的是 i686
接下来的 if 判断没有包括。
`get_url(){
        ......
	bit=`uname -m`
	......
	elif [[ "${bit}" = "i386" ]]; then
        ......
}
`

**Comment by nanqinlang** [comment]
嗯，只写了 i386 的。

**Comment by nanqinlang** [comment]
欢迎提 pr，或我之后加上
