### ISSUE TITLE
内核安装失败

### ISSUE THREAD

**Issue by mouse1130** [tcp-nanqinlang/general#3]
--2017-10-28 14:56:23--  http://elrepo.org/linux/kernel/el7/x86_64/RPMS/kernel-ml-4.13.8-1.el7.elrepo.x86_64.rpm
Resolving elrepo.org (elrepo.org)... 69.195.83.87
Connecting to elrepo.org (elrepo.org)|69.195.83.87|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-10-28 14:56:23 ERROR 404: Not Found.

**Comment by mouse1130** [comment]
下载地址好像不存在

**Comment by ghost** [comment]
官方epel源只放最新mainline内核和longterm，装yum install kernel-ml

**Comment by nanqinlang** [comment]
@mouse1130  
谢谢反馈，官方的 mainline 更新了，所以之前的地址失效了。

**Comment by nanqinlang** [comment]
因为发现 bug，现已移除 `centos` 的脚本，说声抱歉。
