### ISSUE TITLE
关于魔改BBR不要使用最新内核就好了，最新内核会编译失败

### ISSUE THREAD

**Issue by mouse1130** [tcp-nanqinlang/general#4]
关于魔改BBR不要使用最新内核就好了，最新内核会编译失败

**Comment by mouse1130** [comment]
CENTOS可以试试以前的老版内核

**Comment by nanqinlang** [comment]
嗯，谢谢反馈，`centos` 我打算之后再更。

**Comment by nanqinlang** [comment]
这次换到了 `4.12.10` 版本，分别用新装的 centos 6 和 7 进行多次测试均通过。保险起见先放到了本 repo 的 `devel` branch 下。
