### ISSUE TITLE
centos 7 debian也测试了 都不能用啊

### ISSUE THREAD

**Issue by ilovebamboo** [tcp-nanqinlang/general#6]
centos 7 debian也测试了 都不能用
![qq20171202-112450](https://user-images.githubusercontent.com/6214084/33511317-7ba490ea-d753-11e7-84ba-4c29ddc28a87.png)
![qq20171202-112435](https://user-images.githubusercontent.com/6214084/33511318-7bd7b97a-d753-11e7-8643-4dd86e6231f6.png)

**Comment by nanqinlang** [comment]
我已经在另外一个 issue 里回复你了,这个我就关掉咯
