### ISSUE TITLE
作者大人，3.2.1 没有暴力模式了吗？以及如何更新版本的问题。

### ISSUE THREAD

**Issue by sgf** [tcp-nanqinlang/general#8]
linux 新手，有多新，嘛记住的命令也就 apt-get wget sudo 这三个了。
环境：Debian 9 的 KVM VPS上。最新的内核版本 大概是4.13.14。

**问题1：**
今天更新了一下 3.2.1 发现安装的时候没有暴力模式了哇
似乎安装上去后 没有之前的 暴力版本快。
似乎下载东西需要预热一会儿速度才会慢慢提升。
而且似乎没有以前快  以前可以达到2兆，现在最高1兆左右。
**求确认，以及有没有可能加回暴力版本来。**

**问题2：**
另外更新版本的时候 不需要卸载老的版本吧？
（我为了省事没卸载 😂 直接安装了 3.2.1）这样不会有问题吧？

**Comment by nanqinlang** [comment]
脚本更新只是安装方式的更新，加速那个程序（bbr）是不会变的，也就是说只要安装过了就不需要再运行脚本了  
没有选项的话，大概是你到 `输入你要安装的内核版本` 这一步时直接回车了，或者是你用了 `fool` 版本的脚本，就不会有选择暴力的那个选项。

**Comment by sgf** [comment]
噢 我选则版本的时候 输入的不是默认版本。输入的是 4.13.14 版本。没用fool版本。谷歌了一下 fool应该是傻瓜版的意思。。。。
谢谢回复。
