### ISSUE TITLE
希望大佬可以支持xen

### ISSUE THREAD

**Issue by gegehennb** [tcp-nanqinlang/general#9]
上一个版本好像是可以支持xen的，最新版本好像不支持了，但是其实还是有一些人用xen的，希望大佬可以支持下，谢谢大佬

**Comment by nanqinlang** [comment]
`xen` 我没有测试过，我也没用过 xen，所以我现在加了一个 `只允许 KVM` 的条件，之前的版本没有写入这个条件其实是我的失误  
如果你还是想试试能不能在 xen 运行的话，我之后发一个去掉这个条件的版本。

**Comment by nanqinlang** [comment]
这个能在 `xen` 上执行，仅供测试，请在便于重装的机器上使用：
```bash
wget https://github.com/nanqinlang-tcp/tcp_nanqinlang/releases/download/3.3.0-only-test/tcp_nanqinlang-pro-3.3.0-nocheck.sh
bash tcp_nanqinlang-pro-3.3.0-nocheck.sh
```

**Comment by gegehennb** [comment]
谢谢大佬，但是我这周有考试，可能没法测试，下周一定把结果反馈给大佬。谢谢

**Comment by nanqinlang** [comment]
`xen` 这个只是看到这个 issue 了就拿出来给你们玩玩吧。
